FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    (apt-get install -y --fix-missing --no-install-recommends \
    libwayland-dev:arm64 \
    libxkbcommon-dev:arm64 \
    libx11-dev:arm64 \
    libasound2-dev:arm64 \
    libudev-dev:arm64 \
    libegl1-mesa-dev:arm64 \
    libspeechd-dev:arm64 \
    libxcb-render0-dev:arm64 \
    libxcb-shape0-dev:arm64 \
    libxcb-xfixes0-dev:arm64 \
    || (echo "Retrying install..." && apt-get update && apt-get install -y --fix-missing --no-install-recommends \
    libwayland-dev:arm64 \
    libxkbcommon-dev:arm64 \
    libx11-dev:arm64 \
    libasound2-dev:arm64 \
    libudev-dev:arm64 \
    libegl1-mesa-dev:arm64 \
    libspeechd-dev:arm64 \
    libxcb-render0-dev:arm64 \
    libxcb-shape0-dev:arm64 \
    libxcb-xfixes0-dev:arm64)) \
    && rm -rf /var/lib/apt/lists/*
